#############################################################################
# Makefile for building: PBS
# Generated by qmake (2.01a) (Qt 4.5.2) on: Wed Apr 28 21:21:56 2010
# Project:  PBS.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile PBS.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtSql -lQtXml -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		createwalletdialog.cpp \
		createaccountdialog.cpp \
		creditdialog.cpp \
		entrydialog.cpp \
		sheetdialog.cpp \
		aboutdialog.cpp moc_mainwindow.cpp \
		moc_createwalletdialog.cpp \
		moc_createaccountdialog.cpp \
		moc_creditdialog.cpp \
		moc_entrydialog.cpp \
		moc_sheetdialog.cpp \
		moc_aboutdialog.cpp
OBJECTS       = main.o \
		mainwindow.o \
		createwalletdialog.o \
		createaccountdialog.o \
		creditdialog.o \
		entrydialog.o \
		sheetdialog.o \
		aboutdialog.o \
		moc_mainwindow.o \
		moc_createwalletdialog.o \
		moc_createaccountdialog.o \
		moc_creditdialog.o \
		moc_entrydialog.o \
		moc_sheetdialog.o \
		moc_aboutdialog.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		PBS.pro
QMAKE_TARGET  = PBS
DESTDIR       = 
TARGET        = PBS

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_createwalletdialog.h ui_createaccountdialog.h ui_creditdialog.h ui_entrydialog.h ui_sheetdialog.h ui_aboutdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PBS.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtSql.prl \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile PBS.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtSql.prl:
/usr/lib/libQtXml.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile PBS.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/PBS1.0.0 || $(MKDIR) .tmp/PBS1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/PBS1.0.0/ && $(COPY_FILE) --parents mainwindow.h createwalletdialog.h createaccountdialog.h creditdialog.h entrydialog.h sheetdialog.h aboutdialog.h MySQLHeader.h .tmp/PBS1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp createwalletdialog.cpp createaccountdialog.cpp creditdialog.cpp entrydialog.cpp sheetdialog.cpp aboutdialog.cpp .tmp/PBS1.0.0/ && $(COPY_FILE) --parents mainwindow.ui createwalletdialog.ui createaccountdialog.ui creditdialog.ui entrydialog.ui sheetdialog.ui aboutdialog.ui .tmp/PBS1.0.0/ && (cd `dirname .tmp/PBS1.0.0` && $(TAR) PBS1.0.0.tar PBS1.0.0 && $(COMPRESS) PBS1.0.0.tar) && $(MOVE) `dirname .tmp/PBS1.0.0`/PBS1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/PBS1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_createwalletdialog.cpp moc_createaccountdialog.cpp moc_creditdialog.cpp moc_entrydialog.cpp moc_sheetdialog.cpp moc_aboutdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_createwalletdialog.cpp moc_createaccountdialog.cpp moc_creditdialog.cpp moc_entrydialog.cpp moc_sheetdialog.cpp moc_aboutdialog.cpp
moc_mainwindow.cpp: MySQLHeader.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_createwalletdialog.cpp: MySQLHeader.h \
		createwalletdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) createwalletdialog.h -o moc_createwalletdialog.cpp

moc_createaccountdialog.cpp: MySQLHeader.h \
		createaccountdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) createaccountdialog.h -o moc_createaccountdialog.cpp

moc_creditdialog.cpp: MySQLHeader.h \
		creditdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) creditdialog.h -o moc_creditdialog.cpp

moc_entrydialog.cpp: MySQLHeader.h \
		entrydialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) entrydialog.h -o moc_entrydialog.cpp

moc_sheetdialog.cpp: MySQLHeader.h \
		sheetdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) sheetdialog.h -o moc_sheetdialog.cpp

moc_aboutdialog.cpp: aboutdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) aboutdialog.h -o moc_aboutdialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_createwalletdialog.h ui_createaccountdialog.h ui_creditdialog.h ui_entrydialog.h ui_sheetdialog.h ui_aboutdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_createwalletdialog.h ui_createaccountdialog.h ui_creditdialog.h ui_entrydialog.h ui_sheetdialog.h ui_aboutdialog.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_createwalletdialog.h: createwalletdialog.ui
	/usr/bin/uic-qt4 createwalletdialog.ui -o ui_createwalletdialog.h

ui_createaccountdialog.h: createaccountdialog.ui
	/usr/bin/uic-qt4 createaccountdialog.ui -o ui_createaccountdialog.h

ui_creditdialog.h: creditdialog.ui
	/usr/bin/uic-qt4 creditdialog.ui -o ui_creditdialog.h

ui_entrydialog.h: entrydialog.ui
	/usr/bin/uic-qt4 entrydialog.ui -o ui_entrydialog.h

ui_sheetdialog.h: sheetdialog.ui
	/usr/bin/uic-qt4 sheetdialog.ui -o ui_sheetdialog.h

ui_aboutdialog.h: aboutdialog.ui
	/usr/bin/uic-qt4 aboutdialog.ui -o ui_aboutdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		MySQLHeader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		MySQLHeader.h \
		ui_mainwindow.h \
		createwalletdialog.h \
		createaccountdialog.h \
		creditdialog.h \
		aboutdialog.h \
		entrydialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

createwalletdialog.o: createwalletdialog.cpp createwalletdialog.h \
		MySQLHeader.h \
		ui_createwalletdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o createwalletdialog.o createwalletdialog.cpp

createaccountdialog.o: createaccountdialog.cpp createaccountdialog.h \
		MySQLHeader.h \
		ui_createaccountdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o createaccountdialog.o createaccountdialog.cpp

creditdialog.o: creditdialog.cpp creditdialog.h \
		MySQLHeader.h \
		ui_creditdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o creditdialog.o creditdialog.cpp

entrydialog.o: entrydialog.cpp entrydialog.h \
		MySQLHeader.h \
		ui_entrydialog.h \
		sheetdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o entrydialog.o entrydialog.cpp

sheetdialog.o: sheetdialog.cpp sheetdialog.h \
		MySQLHeader.h \
		ui_sheetdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sheetdialog.o sheetdialog.cpp

aboutdialog.o: aboutdialog.cpp aboutdialog.h \
		ui_aboutdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aboutdialog.o aboutdialog.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_createwalletdialog.o: moc_createwalletdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_createwalletdialog.o moc_createwalletdialog.cpp

moc_createaccountdialog.o: moc_createaccountdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_createaccountdialog.o moc_createaccountdialog.cpp

moc_creditdialog.o: moc_creditdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_creditdialog.o moc_creditdialog.cpp

moc_entrydialog.o: moc_entrydialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_entrydialog.o moc_entrydialog.cpp

moc_sheetdialog.o: moc_sheetdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sheetdialog.o moc_sheetdialog.cpp

moc_aboutdialog.o: moc_aboutdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aboutdialog.o moc_aboutdialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

